### ISSUE TITLE
Not the same version between pypi.org and GitHub.

### ISSUE THREAD

**Issue by cute-omega** [gkbrk/hackchat#13]
The "hackchat.py" on the [pypi.org](https://pypi.org/project/hackchat/0.2.0) is not the same as [that on GitHub](https://github.com/gkbrk/hackchat/blob/master/hackchat.py).
Clearly, the one on the pypi.org doesn't have the "whisper" function. It will mislead the users(such as me) who use `pip3 install hackchat`  just as the [README.md](https://github.com/gkbrk/hackchat/blob/master/README.md) said to install the package.
Hope the origin uploader can fix it as soon as possible.

**Comment by gkbrk** [comment]
Wow, haven't pushed this to PyPI in ages. Let's fix that.

**Comment by gkbrk** [comment]
Pushed 0.3.0 to PyPI.
